version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  reviewers:
  - D-Wtnbe
  labels:
    - "dependencies"
    - "automerge"
