version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    # npm プルリクエストのラベルを指定する
    labels:
      - "automerge"
      - "dependencies"
