version: "3.7"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3031:3031
    volumes:
      - ./backend:/var/www/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx/
    links:
      - backend
    ports:
      - 5000:80
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - BACKEND_SERVICE_URL=http://127.0.0.1:3031
      - VUE_GATEWAY_URL=http://127.0.0.1:3007
    stdin_open: true

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ="Asia/Tokyo"
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default_authentication_plugin=mysql_native_password
    volumes:
      - ./database:/docker-entrypoint-initdb.d # docker-entrypoint-initdb.d内のスクリプトは起動時に1度だけ実行される
